Plug 'terrortylor/nvim-comment'
Plug 'nvim-lualine/lualine.nvim'
Plug 'Raimondi/delimitMate'
Plug 'dense-analysis/ale'
Plug 'lukas-reineke/indent-blankline.nvim'
Plug 'Mofiqul/dracula.nvim'
Plug 'ibhagwan/fzf-lua'
Plug 'kyazdani42/nvim-web-devicons'
Plug 'github/copilot.vim'
Plug 'wakatime/vim-wakatime'
Plug 'Pocco81/AutoSave.nvim'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'romgrk/barbar.nvim'
Plug 'akinsho/toggleterm.nvim'
